version: "3.9"

services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - "4002:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: wordpress
    networks:
      - wpsite

  wordpress:
    depends_on:
      - db
    image: wordpress:5.9.2-apache
    ports:
      - "4000:80"
    volumes:
      - wordpress_data:/var/www/html
      - "./wp-content:/var/www/html/wp-content:cached"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      LOCALHOST: 1
      WORDPRESS_DEBUG: 1
      UPLOAD_LIMIT: 300M
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_ENVIRONMENT_TYPE', 'local' );
        define( 'WP_DISABLE_FATAL_ERROR_HANDLER', true );
        define( 'WP_DEBUG_DISPLAY', true );
        define( 'SCRIPT_DEBUG', true );
        define( 'ALLOW_UNFILTERED_UPLOADS', true);
        define( 'WP_POST_REVISIONS', 3 );
        define( 'WP_CACHE', false );
        define( 'WP_MEMORY_LIMIT', '512M' );
    networks:
      - wpsite
networks:
  wpsite:

volumes:
  db_data:
  wordpress_data: